accept_all_with_error_test.exs:##:"test all pass" assert_value failed

-    assert_value "foo"
+    assert_value "foo" == "foo"

Accept new value? [y,n,?] .

  1) test one fail with error (AcceptAllWithErrorTest)
     accept_all_with_error_test.exs:##
     ** (RuntimeError) Error!
     stacktrace:
       accept_all_with_error_test.exs:##: (test)

.
3 tests, 1 failure
